name: azure-iot-identity
base: core24 # the base snap is the execution environment for this snap
version: '1.5.6'
summary: Provides provisioning and cryptographic services for Azure IoT Hub devices.
description: |
  The Identity Service provisions a device's identity and any modules it runs. The device identity can be based
  on symmetric keys or X.509 certificates. It supports manual device registrations or individual/group
  enrollments with the Azure Device Provisioning Service.

license: MIT 

confinement: strict
adopt-info: iot-identity-services

parts:
  configs:
    plugin: dump
    source: ./configs
    organize:
      "package-assets/*": package-assets/${CRAFT_PROJECT_NAME}/
      "secure-assets/*": secure-assets/${SNAPCRAFT_PROJECT_NAME}/
  webserver:
    plugin: dump
    source: ./webserver
    stage-packages:
      - to amd64:
          - libcurl4
          - tpm2-tools
          - tpm2-openssl
          - python3-minimal
          - netcat-openbsd
      - to arm64:
          - libcurl4:arm64
          - tpm2-tools:arm64
          - tpm2-openssl:arm64
          - python3-minimal:arm64
          - netcat-openbsd:arm64
    organize:
      tpm-init.sh: usr/bin/tpm-init.sh
      csr.cnf: usr/bin/csr.cnf
  www:
    plugin: dump
    source: ./www
    organize:
      "*": www/
  web-ui:
    plugin: go
    source: ./webserver/go-program
    build-snaps: ["go/1.26/stable"]
    build-packages:
      - on amd64:
          - libsystemd-dev
          - pkg-config
      - on arm64:
          - libsystemd-dev:arm64
    override-build: |
      cd $SNAPCRAFT_PART_SRC/cmd
      go build -buildvcs=false -o $SNAPCRAFT_PART_INSTALL/usr/bin/web-ui
      case $CRAFT_ARCH_TRIPLET_BUILD_FOR in
        aarch64-linux-gnu)
          export GOARCH=arm64
          export GOARM=7
          export CGO_ENABLED=1
          export CC=aarch64-linux-gnu-gcc
          ;;
        amd64)
          export GOARCH=amd64
          ;;
      esac
      go build -buildvcs=false -o $SNAPCRAFT_PART_INSTALL/usr/bin/web-ui .


  rust-toolchain:
    plugin: nil
    build-packages:
      - curl
    build-environment:
      - BINDGEN_VERSION: '0.69.4'
      - CBINDGEN_VERSION: '0.26.0'
      - PATH: "$PATH:$HOME/.cargo/bin"
    override-build: |
      mkdir -p $HOME/.cargo/bin
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path --profile minimal -y
      cargo install bindgen-cli --version "=$BINDGEN_VERSION"
      cargo install cbindgen --version "=$CBINDGEN_VERSION"
  iot-identity-services:
    build-environment:
      - PATH: "$PATH:$HOME/.cargo/bin"
      - ARCH: "$CRAFT_ARCH_BUILD_FOR"
      - CARGO_PROFILE_RELEASE_DEBUG: 0
    after: [ rust-toolchain ]
    plugin: nil
    source: ./
    build-packages:
      - acl
      - autoconf
      - autoconf-archive
      - automake
      - build-essential
      - clang
      - cmake
      - curl
      - git
      - jq
      - libclang1
      - libltdl-dev
      - libssl-dev
      - libtool
      - libtss2-dev
      - llvm-dev
      - pkg-config
      - to arm64:
        - ca-certificates
        - libcurl4-openssl-dev
    stage-packages:
      - libtss2-esys-3.0.2-0
      - libtss2-rc0
      - libtss2-sys1
      - libtss2-tctildr0
    override-build: |
      # if version contains substring "dev" set grade to devel, else stable
      SC_VERSION="$(craftctl get version)"
      if test "${SC_VERSION#*dev}" != "$SC_VERSION" ; then
        craftctl set grade=devel
      else
        craftctl set grade=stable
      fi
      contrib/third-party-notices.sh > THIRD-PARTY-NOTICES
      make install-deb \
        ARCH=$CRAFT_ARCH_BUILD_FOR \
        RELEASE=1 \
        VENDOR_LIBTSS=0 \
        OPENSSL_ENGINES_DIR="/lib/engines-3" \
        PLATFORM_FEATURES=snapd \
        USER_AZIOTID=root \
        USER_AZIOTCS=root \
        USER_AZIOTKS=root \
        USER_AZIOTTPM=root \
        SOCKET_DIR=/var/sockets/aziot \
        DESTDIR=$CRAFT_PART_INSTALL
    organize:
      usr/: .
    stage:
      - -include
      # - -lib/systemd
      - -var
      - -libexec/aziot-identity-service/aziot-*
    override-prime: |
      craftctl default
      # Recreate expected relative symlinks that were not staged from the install because they link external to the snap
      # and prevent publishing to snapcraft.
      ln -vrfs $CRAFT_PRIME/libexec/aziot-identity-service/aziotd $CRAFT_PRIME/libexec/aziot-certd
      ln -vrfs $CRAFT_PRIME/libexec/aziot-identity-service/aziotd $CRAFT_PRIME/libexec/aziot-identityd
      ln -vrfs $CRAFT_PRIME/libexec/aziot-identity-service/aziotd $CRAFT_PRIME/libexec/aziot-keyd
      ln -vrfs $CRAFT_PRIME/libexec/aziot-identity-service/aziotd $CRAFT_PRIME/libexec/aziot-tpmd
  command-chain:
    plugin: dump
    source: ./contrib
    stage: [ snap/command-chain ]

plugs:
  tpm2-socket:
    interface: content
    content: tpm2-socket
    target: $SNAP_DATA/tpm2-socket
  system-configuration:
    interface: content
    content: system-configuration
    target: $SNAP_DATA/system-configuration

apps:
  tpm-init:
    command: usr/bin/tpm-init.sh
    daemon: simple
    restart-condition: on-failure
    restart-delay: 5s
    plugs: [tpm2-socket, system-configuration, network, network-bind]
  web-ui:
    command: usr/bin/web-ui
    daemon: simple
    restart-condition: always
    plugs: [tpm2-socket, system-configuration, network, network-bind]
    slots:
      - package-assets
      - package-certificates
    passthrough:
      restart-delay: 5s

  aziotctl:
    command: bin/aziotctl
    plugs:
      - log-observe
      - system-observe
      - network
  certd:
    command-chain: [ snap/command-chain/launch-wrapper.sh ]
    command: libexec/aziot-certd
    daemon: simple
    plugs:
      - network-bind
    sockets:
      unix:
        listen-stream: $SNAP_DATA/shared/sockets/aziot/certd.sock
        socket-mode: 0666
  identityd:
    command-chain: [ snap/command-chain/launch-wrapper.sh ]
    command: libexec/aziot-identityd
    daemon: simple
    plugs:
      - network
      - network-bind
    sockets:
      unix:
        listen-stream: $SNAP_DATA/shared/sockets/aziot/identityd.sock
        socket-mode: 0666
  keyd:
    command-chain: [ snap/command-chain/launch-wrapper.sh ]
    command: libexec/aziot-keyd
    daemon: simple
    plugs:
      - network-bind
      - pkcs11
    sockets:
      unix:
        listen-stream: $SNAP_DATA/shared/sockets/aziot/keyd.sock
        socket-mode: 0666
  tpmd:
    command-chain: [ snap/command-chain/launch-wrapper.sh ]
    command: libexec/aziot-tpmd
    daemon: simple
    plugs:
      - network-bind
      - tpm
    sockets:
      unix:
        listen-stream: $SNAP_DATA/shared/sockets/aziot/tpmd.sock
        socket-mode: 0666

hooks:
  configure:
    plugs:
      - hostname-control
      - log-observe
      - mount-observe

slots:
  package-certificates:
    interface: content
    content: package-certificates
    source:
      write:
        - $SNAP_COMMON/package-certificates/${CRAFT_PROJECT_NAME}
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${CRAFT_PROJECT_NAME}
  secure-assets:
    interface: content
    content: secure-assets
    source:
      read:
        - $SNAP/secure-assets/${SNAPCRAFT_PROJECT_NAME}
  package-run:
    interface: content
    content: package-run
    source:
      write:
        - $SNAP_DATA/package-run/${CRAFT_PROJECT_NAME}

  aziotctl-executables:
    interface: content
    content: aziotctl-executables
    source:
      read: [ $SNAP/bin ]
  aziot-keys-openssl-engine:
    interface: content
    content: aziot-keys-openssl-engine
    source:
      read: [ $SNAP/lib/engines-3 ]
  identity-service:
    interface: content
    content: aziot-identity-service
    source:
      write: [ $SNAP_DATA/shared ]

layout:
  /var/lib/aziot:
    symlink: $SNAP_DATA/var/lib/aziot
  /var/secrets/aziot:
    symlink: $SNAP_DATA/shared/secrets/aziot
  /var/sockets/aziot:
    symlink: $SNAP_DATA/shared/sockets/aziot
  /etc/aziot:
    symlink: $SNAP_DATA/shared/config/aziot
